---
# Handlers for work_station role

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: Restart lightdm
  ansible.builtin.service:
    name: lightdm
    state: restarted

- name: Restart crd
  ansible.builtin.systemd:
    name: "chrome-remote-desktop@{{ lookup('env', 'VAR_user_worker') }}"
    state: started
    daemon_reload: true
  failed_when: false

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload udev rules
  ansible.builtin.shell:
    cmd: "udevadm control --reload-rules && udevadm trigger"
    executable: /bin/bash
  changed_when: true
