---
# Handlers for work_station role

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: Restart lightdm
  ansible.builtin.service:
    name: lightdm
    state: restarted

- name: Restart crd
  ansible.builtin.service:
    name: chrome-remote-desktop
    state: restarted
  failed_when: false

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
